### ISSUE TITLE
Publish npm package 📦

### ISSUE THREAD

**Issue by markhobson** [hdpe/jquery-behaviours#2]
Hi @hdpe, firstly thanks for your great library!

I was wondering whether you would be so kind as to publish it to npm please?

Thanks! :smiley:

**Comment by hdpe** [comment]
Released at version 1.0.0 - thank you for shopping with jquery-behaviours! :)

https://www.npmjs.com/package/jquery-behaviours

**Comment by markhobson** [comment]
Thanks so much!
:star::star::star::star::star: _Would shop again_
